-- 코드를 작성해주세요
SELECT 
    DISTINCT D.ID AS ID,
    D.EMAIL AS EMAIL,
    D.FIRST_NAME AS FIRST_NAME,
    D.LAST_NAME AS LAST_NAME
FROM
    SKILLCODES AS SC JOIN
    DEVELOPERS AS D ON (SC.CODE & D.SKILL_CODE) > 0
WHERE
    SC.NAME='C#' OR SC.NAME='Python'
ORDER BY ID ASC
